//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.3625
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Assembly Title")]
[assembly: AssemblyDescription("Assembly Description")]
[assembly: AssemblyCompany("Assembly Company")]
[assembly: AssemblyProduct("Assembly Product")]
[assembly: AssemblyCopyright("Copyright ©  2012")]
[assembly: ComVisible(true)]
[assembly: Guid("620d2828-7604-48e5-b99b-72d567b25732")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.17.4484")]
[assembly: AssemblyInformationalVersion("1.0.17.4484")]


